"""Retexture an existing Meshy model from one approved style image.

Authentication is read by forge.py from MESHY_API_KEY or the gitignored
tools/art-forge/meshy.key file. Geometry is not regenerated by this command.
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import forge


def _download_textures(status: dict, output: Path) -> int:
    """Download every texture map returned by Meshy beside the GLB."""
    count = 0
    texture_dir = output.with_name(output.stem + "_textures")
    for index, texture_set in enumerate(status.get("texture_urls") or []):
        for kind, url in (texture_set or {}).items():
            if not url:
                continue
            suffix = f"_{index}" if index else ""
            try:
                forge._download(url, texture_dir / f"{output.stem}{suffix}_{kind}.png")
                count += 1
            except Exception as exc:
                print(f"texture {kind} failed: {exc}", flush=True)
    return count


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Texture an existing Meshy model from a concept image without changing geometry."
    )
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--input-task-id", help="Successful Meshy Image-to-3D task id")
    source.add_argument("--model-url", help="Public GLB/GLTF/FBX/OBJ/USDZ model URL")
    parser.add_argument("--style-image", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--texture-resolution", default="4k", choices=("1k", "2k", "4k"))
    parser.add_argument("--ai-model", default="latest")
    parser.add_argument(
        "--new-uv",
        action="store_true",
        help="Let Meshy unwrap new UVs; the default preserves the source model's original UVs.",
    )
    args = parser.parse_args()

    if not args.style_image.is_file():
        parser.error(f"missing style image: {args.style_image}")

    key = forge.meshy_key()
    if not key:
        parser.error(
            "No Meshy API key. Set MESHY_API_KEY or use the gitignored tools/art-forge/meshy.key."
        )

    prepared_style = forge._prepare_image(args.style_image)
    body = {
        "image_style_url": forge._data_uri(prepared_style),
        "ai_model": args.ai_model,
        "enable_original_uv": not args.new_uv,
        "enable_pbr": True,
        "texture_resolution": args.texture_resolution,
        "remove_lighting": True,
        "target_formats": ["glb"],
    }
    if args.input_task_id:
        body["input_task_id"] = args.input_task_id
    else:
        body["model_url"] = args.model_url

    print(
        f"style: {args.style_image.name} ({prepared_style.stat().st_size / 1024:.0f} KB prepared)",
        flush=True,
    )
    print(
        "settings: texture-only, original UVs="
        f"{body['enable_original_uv']}, PBR, {args.texture_resolution}, lighting removal",
        flush=True,
    )

    created = forge._meshy_request("POST", "/retexture", key, body, timeout=180)
    task_id = created.get("result")
    if not task_id:
        raise RuntimeError(f"Meshy did not return a retexture task id: {created}")
    print(f"Meshy retexture task {task_id}", flush=True)

    last_progress = -1
    status: dict = {}
    while True:
        time.sleep(forge.MESHY_POLL_SECONDS)
        status = forge._meshy_request("GET", f"/retexture/{task_id}", key)
        state = status.get("status")
        progress = int(status.get("progress") or 0)
        if progress != last_progress:
            print(f"progress={progress}% status={state}", flush=True)
            last_progress = progress
        if state in ("SUCCEEDED", "FAILED", "CANCELED"):
            break

    if status.get("status") != "SUCCEEDED":
        detail = (status.get("task_error") or {}).get("message", "no detail")
        raise RuntimeError(f"Meshy retexture {status.get('status')}: {detail}")

    glb_url = (status.get("model_urls") or {}).get("glb")
    if not glb_url:
        raise RuntimeError("Meshy returned no GLB URL")

    size = forge._download(glb_url, args.output)
    texture_count = _download_textures(status, args.output)
    result = {
        "ok": True,
        "backend": "meshy-retexture",
        "task_id": task_id,
        "source_task_id": args.input_task_id,
        "output": str(args.output),
        "size_bytes": size,
        "texture_maps": texture_count,
        "consumed_credits": status.get("consumed_credits"),
    }
    print(json.dumps(result), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
